/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 3.glb -T 
Files: 3.glb [4.81MB] > /Users/marispopovs/Downloads/PM react/public/3-transformed.glb [348.1KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model3(props) {
  const { nodes, materials } = useGLTF('/3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3-8-4k'].geometry} material={materials['3-8-4k']} />
    </group>
  )
}

useGLTF.preload('/3-transformed.glb')
