/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 5.glb -T 
Files: 5.glb [5.2MB] > /Users/marispopovs/Downloads/PM react/public/5-transformed.glb [586.29KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model5(props) {
  const { nodes, materials } = useGLTF('/5-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['5-10-4k'].geometry} material={materials['5-10-4k']} />
    </group>
  )
}

useGLTF.preload('/5-transformed.glb')
