/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 6.glb -T 
Files: 6.glb [4.71MB] > /Users/marispopovs/Downloads/PM react/public/6-transformed.glb [452.39KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model6(props) {
  const { nodes, materials } = useGLTF('/6-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6-10-4k'].geometry} material={materials['6-10-4k']} />
    </group>
  )
}

useGLTF.preload('/6-transformed.glb')
