/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 7c.glb -T 
Files: 7c.glb [2.44MB] > /Users/marispopovs/Downloads/sandbox/public/7c-transformed.glb [211.25KB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Link, useLocation } from 'wouter';

export function Putns(props) {
  const [, setLocation] = useLocation(); // Get setLocation function
  const { nodes, materials } = useGLTF('/7c-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
      onClick={() => setLocation('/dream')} 
      geometry={nodes['7-8-4k'].geometry} material={materials['7-8-4k']} />
    </group>
  )
}

useGLTF.preload('/7c-transformed.glb')
