/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 9.glb -T 
Files: 9.glb [5.05MB] > /Users/marispopovs/Downloads/PM react/public/9-transformed.glb [384.76KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model9(props) {
  const { nodes, materials } = useGLTF('/9-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['9-10-4k'].geometry} material={materials['9-10-4k']} />
    </group>
  )
}

useGLTF.preload('/9-transformed.glb')
