/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 color_tube.glb -T -d 
Files: color_tube.glb [3.31MB] > /Users/marispopovs/Downloads/sandbox/public/color_tube-transformed.glb [335.37KB] (90%)
Author: popovs (https://sketchfab.com/popovs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/color-tube-a305a4114fe6420bbf80fefcba954375
Title: Color tube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tube(props) {
  const { nodes, materials } = useGLTF('/color_tube-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} position={[-0.124, -0.059, 0.07]} rotation={[1.7, 0.385, -0.426]} />
    </group>
  )
}

useGLTF.preload('/color_tube-transformed.glb')
