/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 jautraisAR.glb -T 
Files: jautraisAR.glb [2.32MB] > /Users/marispopovs/Downloads/PM react/public/jautraisAR-transformed.glb [165.12KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jautrais(props) {
  const { nodes, materials } = useGLTF('/jautraisAR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.for_Blender.geometry} material={materials.for_Blender} rotation={[Math.PI, -1.061, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/jautraisAR-transformed.glb')
