/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lauva.glb -T 
Files: lauva.glb [5.63MB] > /Users/marispopovs/Downloads/PM react/public/lauva-transformed.glb [507.49KB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lauva(props) {
  const { nodes, materials } = useGLTF('/lauva-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4k_t-n'].geometry} material={materials['4k_t-n']} />
    </group>
  )
}

useGLTF.preload('/lauva-transformed.glb')
